spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyon?serverTimezone=Asia/Seoul
    username: root
    password: 0113

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080
